language: java

jdk:
  - openjdk8

script:
  # tests are not done with mvn test - dont know why
  - mvn verify cobertura:cobertura

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:

  - provider: script
    skip_cleanup: true
    script: bash scripts/deploy_doc.sh
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH = "develop" || $TRAVIS_TAG
